"""added datetime to user schema

Revision ID: 26822db186cf
Revises: 2f9485433416
Create Date: 2023-08-03 21:46:17.080328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26822db186cf'
down_revision = '2f9485433416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.drop_column('date_posted')

    # ### end Alembic commands ###
