"""added date posted to dictioanry model

Revision ID: 69bf38e93fcb
Revises: 0ef9e4581561
Create Date: 2023-08-07 09:56:05.270019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69bf38e93fcb'
down_revision = '0ef9e4581561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.drop_column('date_posted')

    # ### end Alembic commands ###
